version: '3.8'

services:
  nfs-server:
    image: gists/nfs-server:latest
    container_name: team-nfs-server
    privileged: true
    environment:
      - NFS_DIR=/nfs-share
      - NFS_OPTION=rw,fsid=0,async,no_subtree_check,no_auth_nlm,insecure,no_root_squash
    volumes:
      - /workdisk/infrastructure/data/nfs-data:/nfs-share
    ports:
      - "2049:2049"
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: team-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    volumes:
      - /workdisk/infrastructure/data/mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: team-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=qwen_users
    volumes:
      - /workdisk/infrastructure/data/postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  gitea:
    image: docker.gitea.com/gitea:1.25.2
    container_name: team-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - LOGIN_ID=admin/admin@demo.com
      - LOGIN_PASSWORD=admin123
    restart: unless-stopped
    volumes:
      - /workdisk/infrastructure/data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "222:22"

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: team-excalidraw
    restart: unless-stopped
    volumes:
      - /workdisk/infrastructure/data/excalidraw:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:80"

  drawio:
    image: jgraph/drawio
    container_name: team-drawio
    restart: unless-stopped
    volumes:
      - /workdisk/infrastructure/data/drawio:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8008:8080"
      - "8443:8443"

volumes:
  mongo-data:
  postgres-data:

networks:
  team-network:
    driver: bridge
